version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - redis
    volumes:
      - .:/app

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker.py
    environment:
      - WORKER_ID=1
    depends_on:
      - redis
    volumes:
      - .:/app

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker.py
    environment:
      - WORKER_ID=2
    depends_on:
      - redis
    volumes:
      - .:/app

  worker3:
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker.py
    environment:
      - WORKER_ID=3
    depends_on:
      - redis
    volumes:
      - .:/app

  worker4:
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker.py
    environment:
      - WORKER_ID=4
    depends_on:
      - redis
    volumes:
      - .:/app
